name: Petclinic CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: maven

      - name: Give permission to Maven Wrapper
        run: chmod +x mvnw

      - name: Run tests
        run: ./mvnw test

      - name: Build application
        run: ./mvnw package -DskipTests
